[2022-02-10 16:08:21,030] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_2_gcs_dag.bq_ext_2_part_task manual__2022-02-10T15:51:47.943190+00:00 [queued]>
[2022-02-10 16:08:21,051] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_2_gcs_dag.bq_ext_2_part_task manual__2022-02-10T15:51:47.943190+00:00 [queued]>
[2022-02-10 16:08:21,053] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:08:21,055] {taskinstance.py:1239} INFO - Starting attempt 5 of 6
[2022-02-10 16:08:21,056] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:08:21,075] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2022-02-10 15:51:47.943190+00:00
[2022-02-10 16:08:21,083] {standard_task_runner.py:52} INFO - Started process 906 to run task
[2022-02-10 16:08:21,088] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_2_gcs_dag', 'bq_ext_2_part_task', 'manual__2022-02-10T15:51:47.943190+00:00', '--job-id', '921', '--raw', '--subdir', 'DAGS_FOLDER/data-2-gcs-dag.py', '--cfg-path', '/tmp/tmpe1t30f85', '--error-file', '/tmp/tmpsdf1d4ku']
[2022-02-10 16:08:21,090] {standard_task_runner.py:77} INFO - Job 921: Subtask bq_ext_2_part_task
[2022-02-10 16:08:21,173] {logging_mixin.py:109} INFO - Running <TaskInstance: data_2_gcs_dag.bq_ext_2_part_task manual__2022-02-10T15:51:47.943190+00:00 [running]> on host c1978c8f7cc5
[2022-02-10 16:08:21,240] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_2_gcs_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-10T15:51:47.943190+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-10T15:51:47.943190+00:00
[2022-02-10 16:08:21,242] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-02-10 16:08:21,245] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:08:21,256] {bigquery.py:1637} INFO - Inserting job ***_data_2_gcs_dag_bq_ext_2_part_task_2022_02_10T15_51_47_943190_00_00_be9fb914bd1796360ab292b93a0cba7c
[2022-02-10 16:08:21,684] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset vaulted-art-339212:trips_data_all was not found in location europe-west3

(job ID: airflow_data_2_gcs_dag_bq_ext_2_part_task_2022_02_10T15_51_47_943190_00_00_be9fb914bd1796360ab292b93a0cba7c)

                           -----Query Job SQL Follows-----                            

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE taxi-rides-ny.nytaxi.yellow_tripdata_partitoned_clustered
   2:        PARTITION BY DATE(tpep_pickup_datetime)
   3:        CLUSTER BY VendorID AS
   4:        SELECT * FROM trips_data_all.external_yellow_tripdata
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-02-10 16:08:21,727] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_2_gcs_dag, task_id=bq_ext_2_part_task, execution_date=20220210T155147, start_date=20220210T160821, end_date=20220210T160821
[2022-02-10 16:08:21,763] {standard_task_runner.py:92} ERROR - Failed to execute job 921 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset vaulted-art-339212:trips_data_all was not found in location europe-west3

(job ID: airflow_data_2_gcs_dag_bq_ext_2_part_task_2022_02_10T15_51_47_943190_00_00_be9fb914bd1796360ab292b93a0cba7c)

                           -----Query Job SQL Follows-----                            

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE taxi-rides-ny.nytaxi.yellow_tripdata_partitoned_clustered
   2:        PARTITION BY DATE(tpep_pickup_datetime)
   3:        CLUSTER BY VendorID AS
   4:        SELECT * FROM trips_data_all.external_yellow_tripdata
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-02-10 16:08:21,834] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-10 16:08:21,912] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
