[2022-02-01 21:55:54,155] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-02-01 21:55:54,167] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [queued]>
[2022-02-01 21:55:54,169] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 21:55:54,169] {taskinstance.py:1239} INFO - Starting attempt 6 of 6
[2022-02-01 21:55:54,170] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 21:55:54,186] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2021-01-02 06:00:00+00:00
[2022-02-01 21:55:54,193] {standard_task_runner.py:52} INFO - Started process 2073 to run task
[2022-02-01 21:55:54,197] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-01-02T06:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp738rgg3a', '--error-file', '/tmp/tmppzkr55tv']
[2022-02-01 21:55:54,203] {standard_task_runner.py:77} INFO - Job 86: Subtask ingest
[2022-02-01 21:55:54,291] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-01-02T06:00:00+00:00 [running]> on host 4eaca4839574
[2022-02-01 21:55:54,354] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-01 21:55:54,380] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T06:00:00+00:00
[2022-02-01 21:55:54,382] {logging_mixin.py:109} INFO - yellow_taxi_2021_01 /opt/***/output_2021-01.csv
[2022-02-01 21:57:37,298] {logging_mixin.py:109} INFO - inserted another chunk, took 50.031 second
[2022-02-01 21:58:26,562] {logging_mixin.py:109} INFO - inserted another chunk, took 49.263 second
[2022-02-01 21:59:17,207] {logging_mixin.py:109} INFO - inserted another chunk, took 50.644 second
[2022-02-01 22:00:08,124] {logging_mixin.py:109} INFO - inserted another chunk, took 50.916 second
[2022-02-01 22:00:59,359] {logging_mixin.py:109} INFO - inserted another chunk, took 51.234 second
[2022-02-01 22:01:50,514] {logging_mixin.py:109} INFO - inserted another chunk, took 51.153 second
[2022-02-01 22:02:44,236] {logging_mixin.py:109} INFO - inserted another chunk, took 53.721 second
[2022-02-01 22:03:38,184] {logging_mixin.py:109} INFO - inserted another chunk, took 53.946 second
[2022-02-01 22:04:31,865] {logging_mixin.py:109} INFO - inserted another chunk, took 53.680 second
[2022-02-01 22:05:28,946] {logging_mixin.py:109} INFO - inserted another chunk, took 57.079 second
[2022-02-01 22:06:27,810] {logging_mixin.py:109} INFO - inserted another chunk, took 58.864 second
[2022-02-01 22:06:28,011] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:174: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  return_value = self.execute_callable()

[2022-02-01 22:07:24,917] {logging_mixin.py:109} INFO - inserted another chunk, took 57.105 second
[2022-02-01 22:08:01,530] {logging_mixin.py:109} INFO - inserted another chunk, took 36.612 second
[2022-02-01 22:08:01,532] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 31, in ingest_callable
    df = next(df_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1024, in __next__
    return self.get_chunk()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1074, in get_chunk
    return self.read(nrows=size)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 826, in pandas._libs.parsers.TextReader.read_low_memory
StopIteration
[2022-02-01 22:08:01,549] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210102T060000, start_date=20220201T215554, end_date=20220201T220801
[2022-02-01 22:08:01,565] {standard_task_runner.py:92} ERROR - Failed to execute job 86 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 31, in ingest_callable
    df = next(df_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1024, in __next__
    return self.get_chunk()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1074, in get_chunk
    return self.read(nrows=size)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 826, in pandas._libs.parsers.TextReader.read_low_memory
StopIteration
[2022-02-01 22:08:01,652] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-01 22:08:01,690] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
